spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.yicj.study.provider: trace

mybatis-plus:
  type-aliases-package: com.yicj.study.provider.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml
